- hosts: controllers
  connection: ssh
  roles:
    - etcd
    - control_plane
    - nginx_heath_check_proxy

- hosts: controller-0
  connection: ssh
  roles:
    - rbac_config

- hosts: workers
  connection: ssh
  roles:
    - worker_deps_binaries